### PR TITLE
Add social preview images for pipelines / repos

### PR DESCRIPTION
**Pull request by MaxUlysse**
- Add social preview images for pipelines / repos.
- Include script to generate all pngs based on the svgs provided availability of inkscape + maven pro font:

```console
$ ./generate_png.sh 
Background RRGGBBAA: ffffffff
Area 0:0:1280:640 exported to 1280 x 640 pixels (96 dpi)
Bitmap saved as: png/ampliseq.png
[...]
Background RRGGBBAA: ffffffff
Area 0:0:1280:640 exported to 1280 x 640 pixels (96 dpi)
Bitmap saved as: png/vipr.png
```

### CODE REVIEW

**Comment by ewels** [comment]
Thanks @MaxUlysse, looking good! I think we should probably omit the actual workflow logos though - these should go in the pipeline repositories if anywhere. But having the template and script is definitely good to have 👍

**Comment by MaxUlysse** [comment]
Good point, I'll remove them

**Comment by MaxUlysse** [comment]
I just kept the png version of the template

**Comment by ewels** [comment]
Nice - do we need the svgs too? Are they not also auto-generated by the script?

**Comment by MaxUlysse** [comment]
No, the script only generate the pngs from the svgs, I manually did generate the svgs

**Comment by ewels** [comment]
ok, right. Hmm. I still think that any pipeline-specific assets should go in the pipeline repositories though. 

Fancy making ~40 PRs to different repos with PNG+SVG files? Ideally with standard filenames: `/assets/nf-core-sarek_social_preview.svg`

Then keep just the template and associated files in this PR.

**Comment by MaxUlysse** [comment]
I can do that, I might slightly hate you for it, but I'll be gaining points in the Contributor Leaderboard, so it'll be all right in the end.
Then we actually won't need this PR in the end, as the template was already there.
Maybe it could be included in tools?

**Pull request closed without merging**
